// ./Inbox/config/taskCardsConfig.ts
import { PlayIcon, ReviewFormsIcon, PersonIcon, AgendaIcon } from "../assets/Icons";
import { TaskCardConfig } from "../organisms/PrioritySwimLanes";

export const getTaskCardsConfig = (
  urgentTaskCounts: { high: number; medium: number; low: number; assigned_to_me: number; created_by_me: number },
  birthdayCount: number,
  agendaCount: number,
  messagesCount: number,
  applicantCount: number
): TaskCardConfig[] => [
  {
    id: "urgent-tasks-high",
    title: "Urgent Tasks",
    count: urgentTaskCounts.high,
    icon: <PlayIcon />,
    variant: "urgent",
    priority: "high",
    testId: "task-block-expedite-queue",
  },
  {
    id: "review-forms-high",
    title: "Review Forms",
    count: 8,
    icon: <ReviewFormsIcon />,
    variant: "normal",
    priority: "high",
    testId: "task-block-needs-review",
  },
  {
    id: "review-prescriptions",
    title: "Review Prescriptions",
    count: 7,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "high",
    testId: "task-block-prescriptions",
  },
  {
    id: "pending-too-long",
    title: "Pending Too Long",
    count: 2,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "high",
    testId: "task-block-aging-tasks",
  },
  {
    id: "treatment-reviews",
    title: "Treatment Reviews",
    count: 0,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "high",
    testId: "task-block-treatment-reviews",
  },
  {
    id: "urgent-tasks-medium",
    title: "Urgent Tasks",
    count: urgentTaskCounts.medium,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "medium",
    testId: "task-block-expedite-queue",
  },
  {
    id: "review-forms-medium",
    title: "Review Forms",
    count: 12,
    icon: <ReviewFormsIcon />,
    variant: "normal",
    priority: "medium",
    testId: "task-block-needs-review-medium",
  },
  // {
  //   id: "all-reminders",
  //   title: "All Reminders",
  //   count: urgentTaskCounts.high + urgentTaskCounts.medium + urgentTaskCounts.low,
  //   icon: <PlayIcon />,
  //   variant: "normal",
  //   priority: "medium",
  //   testId: "task-block-suggested-actions",
  // },
  {
    id: "assigned-to-me",
    title: "Assigned to Me",
    count: urgentTaskCounts.assigned_to_me,
    icon: <PersonIcon />,
    variant: "normal",
    priority: "medium",
    testId: "task-block-assigned-to-me",
  },
  {
    id: "tasks-created-by-me",
    title: "Tasks Created by Me",
    count: urgentTaskCounts.created_by_me,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "medium",
    testId: "task-block-created-by-me",
  },
  {
    id: "urgent-tasks-low",
    title: "Urgent Tasks",
    count: urgentTaskCounts.low,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "low",
    testId: "task-block-expedite-queue",
  },
  {
    id: "birthdays",
    title: "Birthdays",
    count: birthdayCount,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "low",
    testId: "task-block-fyi-zone",
  },
  // Everything Else
  {
    id: "messages",
    title: "Messages",
    count: messagesCount,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "other",
    testId: "task-block-messages",
  },
  {
    id: "applicants",
    title: "Applicants",
    count: applicantCount,
    icon: <PlayIcon />,
    variant: "normal",
    priority: "other",
    testId: "task-block-applicants",
  },
  {
    id: "agenda",
    title: "Agenda",
    count: agendaCount,
    icon: <AgendaIcon />,
    variant: "normal",
    priority: "other",
    testId: "task-block-agenda",
  },
];